import type { BillingPlanDefinition } from './types.js';

export const defaultBillingPlans: readonly BillingPlanDefinition[] = [
  {
    id: 'plan_free',
    code: 'free',
    name: 'Free',
    description: 'Baseline workspace protection for small teams and evaluation environments.',
    cadence: 'monthly',
    currency: 'usd',
    priceCents: 0,
    quota: [
      { resource: 'ai_review_request', included: 75, softLimit: 60, hardLimit: 90, unit: 'count' },
      { resource: 'tokens_consumed', included: 250000, softLimit: 200000, hardLimit: 300000, unit: 'tokens' },
      { resource: 'repositories_connected', included: 3, softLimit: 3, hardLimit: 5, unit: 'count' },
      { resource: 'prs_reviewed', included: 100, softLimit: 80, hardLimit: 120, unit: 'count' },
      { resource: 'api_calls', included: 2500, softLimit: 2000, hardLimit: 4000, unit: 'count' },
      { resource: 'storage_usage_bytes', included: 5_000_000_000, softLimit: 4_000_000_000, hardLimit: 6_000_000_000, unit: 'bytes' },
      { resource: 'active_seats', included: 3, softLimit: 3, hardLimit: 5, unit: 'seats' },
    ],
    featured: false,
    active: true,
    sortOrder: 0,
    popular: false,
    providerProductId: null,
    providerPriceId: null,
  },
  {
    id: 'plan_team',
    code: 'team',
    name: 'Team',
    description: 'Quota-balanced plan for growing product engineering teams.',
    cadence: 'monthly',
    currency: 'usd',
    priceCents: 4900,
    quota: [
      { resource: 'ai_review_request', included: 500, softLimit: 400, hardLimit: 700, unit: 'count' },
      { resource: 'tokens_consumed', included: 1_500_000, softLimit: 1_200_000, hardLimit: 2_000_000, unit: 'tokens' },
      { resource: 'repositories_connected', included: 25, softLimit: 20, hardLimit: 40, unit: 'count' },
      { resource: 'prs_reviewed', included: 800, softLimit: 650, hardLimit: 1_000, unit: 'count' },
      { resource: 'api_calls', included: 20_000, softLimit: 16_000, hardLimit: 30_000, unit: 'count' },
      { resource: 'storage_usage_bytes', included: 50_000_000_000, softLimit: 40_000_000_000, hardLimit: 70_000_000_000, unit: 'bytes' },
      { resource: 'active_seats', included: 15, softLimit: 12, hardLimit: 25, unit: 'seats' },
    ],
    featured: true,
    active: true,
    sortOrder: 10,
    popular: true,
    providerProductId: null,
    providerPriceId: null,
  },
  {
    id: 'plan_enterprise',
    code: 'enterprise',
    name: 'Enterprise',
    description: 'High-volume governance, SSO-ready controls, and custom support.',
    cadence: 'monthly',
    currency: 'usd',
    priceCents: 0,
    quota: [
      { resource: 'ai_review_request', included: 5_000, softLimit: 4_000, hardLimit: 10_000, unit: 'count' },
      { resource: 'tokens_consumed', included: 25_000_000, softLimit: 20_000_000, hardLimit: 40_000_000, unit: 'tokens' },
      { resource: 'repositories_connected', included: 250, softLimit: 200, hardLimit: 500, unit: 'count' },
      { resource: 'prs_reviewed', included: 10_000, softLimit: 8_000, hardLimit: 20_000, unit: 'count' },
      { resource: 'api_calls', included: 500_000, softLimit: 400_000, hardLimit: 750_000, unit: 'count' },
      { resource: 'storage_usage_bytes', included: 500_000_000_000, softLimit: 400_000_000_000, hardLimit: 750_000_000_000, unit: 'bytes' },
      { resource: 'active_seats', included: 250, softLimit: 200, hardLimit: 500, unit: 'seats' },
    ],
    featured: false,
    active: true,
    sortOrder: 20,
    popular: false,
    providerProductId: null,
    providerPriceId: null,
  },
] as const;

export function findDefaultBillingPlan(code: string): BillingPlanDefinition | null {
  return defaultBillingPlans.find((plan) => plan.code === code) ?? null;
}